name: Run built website against lighthouse

on: [push, pull_request]

jobs:
  hugo-build:
    uses: ./.github/workflows/build.yaml

  lighthouse:
    needs: hugo-build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - name: Download Hugo Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo_build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ".github/workflows/lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
